"""Origin fixup automation for Anubis-on-Nine.

Automates the origin dance fixups:
  - anubis-origin-shim.php  (restores HTTP_HOST from X-Forwarded-Host)
  - .user.ini               (auto_prepend_file, with Wordfence chaining)
  - .htaccess               (trailing-slash 301 fixup, conditional on X-Forwarded-Host)

Both fixups are conditional on X-Forwarded-Host, so they are no-ops for
vhosts sharing the webroot that are NOT behind Anubis. This safety property
is verified before applying — apply() refuses if the file templates drift.

File I/O goes through a FileOps abstraction so tests use local Path
operations while production uses nine-su heredoc commands.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from enum import Enum

from .fileops import FileOps
from .validate import validate_filename, validate_path


# --- File templates (verbatim from the tested runbook) -----------------------

SHIM_PHP = """\
<?php
// Behind Anubis: the origin vhost is reached under a private hostname.
// Restore the public hostname the visitor actually used.
if (!empty($_SERVER['HTTP_X_FORWARDED_HOST'])) {
    $h = explode(',', $_SERVER['HTTP_X_FORWARDED_HOST'])[0];
    $_SERVER['HTTP_HOST'] = $_SERVER['SERVER_NAME'] = trim($h);
}
"""

HTACCESS_BLOCK = """\
# --- Anubis origin fixups (keep above any app rules) ---------------------
# This vhost is only reached through Anubis, which rewrites the Host header to
# the private origin name. Apache would therefore emit its own redirects (e.g.
# mod_dir's missing-trailing-slash 301) pointing at that private name, which
# does not resolve for visitors. Emit them against the public host instead.
<IfModule mod_rewrite.c>
  RewriteEngine On
  RewriteCond %{HTTP:X-Forwarded-Host} ^(.+)$
  RewriteCond %{REQUEST_FILENAME} -d
  RewriteCond %{REQUEST_URI} !/$
  RewriteRule ^(.*)$ https://%{HTTP:X-Forwarded-Host}/$1/ [R=301,L]
</IfModule>
# ------------------------------------------------------------------------
"""

HTACCESS_BLOCK_START = "# --- Anubis origin fixups"
HTACCESS_BLOCK_END = "# ------------------------------------------------------------------------"

CHAIN_TEMPLATE = """\
<?php
// anubis-prepend-chain.php — chains Anubis shim + existing auto_prepend
// Generated by nine-manage-anubis. Anubis shim runs FIRST so HTTP_HOST is
// restored before the WAF/app sees it.
include_once __DIR__ . '/anubis-origin-shim.php';
include_once __DIR__ . '/{existing_basename}';
"""

PREPEND_RE = re.compile(
    r"^\s*auto_prepend_file\s*=\s*['\"]?(.+?)['\"]?\s*$",
    re.MULTILINE,
)

SAFETY_TOKENS = (
    "HTTP_X_FORWARDED_HOST",
    "%{HTTP:X-Forwarded-Host}",
)


def _verify_safety() -> None:
    assert SAFETY_TOKENS[0] in SHIM_PHP, (
        "anubis-origin-shim.php lost its X-Forwarded-Host guard"
    )
    assert SAFETY_TOKENS[1] in HTACCESS_BLOCK, (
        ".htaccess block lost its X-Forwarded-Host RewriteCond"
    )


# --- State -------------------------------------------------------------------


class UserIniState(Enum):
    ABSENT = "absent"
    PRESENT_NO_PREPEND = "present_no_prepend"
    PRESENT_PREPEND_OTHER = "present_prepend_other"
    PRESENT_PREPEND_SHIM = "present_prepend_shim"
    PRESENT_PREPEND_CHAIN = "present_prepend_chain"


class HtaccessState(Enum):
    ABSENT = "absent"
    PRESENT_NO_BLOCK = "present_no_block"
    PRESENT_WITH_BLOCK = "present_with_block"


@dataclass
class FixupState:
    user_ini: UserIniState
    htaccess: HtaccessState
    shim_present: bool
    chain_present: bool
    existing_prepend_path: str | None = None
    chain_chained_path: str | None = None

    def is_complete(self) -> bool:
        user_ini_done = self.user_ini in (
            UserIniState.PRESENT_PREPEND_SHIM,
            UserIniState.PRESENT_PREPEND_CHAIN,
        )
        return user_ini_done and self.htaccess is HtaccessState.PRESENT_WITH_BLOCK


@dataclass
class FixupPlan:
    webroot: str
    state: FixupState
    steps: list[str] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)

    @property
    def would_change(self) -> bool:
        return bool(self.steps)


# --- Path helpers ------------------------------------------------------------


def _webroot_path(webroot: str, name: str) -> str:
    """Join a name onto the webroot, proving the result is a safe path.

    Every path FileOps touches comes through here, and RemoteFileOps quotes
    it into a `sudo nine-su` command — so this is the chokepoint that keeps
    a name read back out of a webroot file from escaping its quotes.
    """
    return validate_path(f"{webroot.rstrip('/')}/{name}", field="webroot path")


# --- Detection ---------------------------------------------------------------


def detect_state(webroot: str, ops: FileOps) -> FixupState:
    """Inspect the webroot and return its current fixup state."""
    user_ini_path = _webroot_path(webroot, ".user.ini")
    htaccess_path = _webroot_path(webroot, ".htaccess")
    shim_path = _webroot_path(webroot, "anubis-origin-shim.php")
    chain_path = _webroot_path(webroot, "anubis-prepend-chain.php")

    user_ini_content = ops.read(user_ini_path)
    htaccess_content = ops.read(htaccess_path)
    shim_present = ops.exists(shim_path)
    chain_present = ops.exists(chain_path)

    existing_prepend: str | None = None
    if user_ini_content is None:
        ui_state = UserIniState.ABSENT
    else:
        m = PREPEND_RE.search(user_ini_content)
        if m is None:
            ui_state = UserIniState.PRESENT_NO_PREPEND
        else:
            existing_prepend = m.group(1).strip()
            target = existing_prepend.rsplit("/", 1)[-1]
            if target == "anubis-origin-shim.php":
                ui_state = UserIniState.PRESENT_PREPEND_SHIM
            elif target == "anubis-prepend-chain.php":
                ui_state = UserIniState.PRESENT_PREPEND_CHAIN
            else:
                ui_state = UserIniState.PRESENT_PREPEND_OTHER

    if htaccess_content is None:
        ht_state = HtaccessState.ABSENT
    elif HTACCESS_BLOCK_START in htaccess_content:
        ht_state = HtaccessState.PRESENT_WITH_BLOCK
    else:
        ht_state = HtaccessState.PRESENT_NO_BLOCK

    chain_chained_path: str | None = None
    if chain_present:
        chain_content = ops.read(chain_path) or ""
        includes = re.findall(
            r"include_once\s+__DIR__\s*\.\s*'/(.+?)'", chain_content
        )
        if len(includes) >= 2:
            # Read back out of the operator's own PHP file — untrusted, and
            # it gets joined onto the webroot and quoted into a command.
            chain_chained_path = validate_filename(
                includes[1],
                field="chained include in anubis-prepend-chain.php",
            )

    return FixupState(
        user_ini=ui_state,
        htaccess=ht_state,
        shim_present=shim_present,
        chain_present=chain_present,
        existing_prepend_path=existing_prepend,
        chain_chained_path=chain_chained_path,
    )


# --- Planning ----------------------------------------------------------------


def plan(webroot: str, ops: FileOps) -> FixupPlan:
    """Return what apply() would do, without doing it."""
    _verify_safety()
    state = detect_state(webroot, ops)
    p = FixupPlan(webroot=webroot, state=state)

    shim_path = _webroot_path(webroot, "anubis-origin-shim.php")

    if not state.shim_present:
        p.steps.append("write anubis-origin-shim.php")
    else:
        shim_content = ops.read(shim_path) or ""
        if shim_content != SHIM_PHP:
            p.steps.append("update anubis-origin-shim.php (content drifted)")

    if state.user_ini is UserIniState.ABSENT:
        p.steps.append("create .user.ini pointing at anubis-origin-shim.php")
    elif state.user_ini is UserIniState.PRESENT_NO_PREPEND:
        p.steps.append("backup .user.ini, add auto_prepend_file line")
    elif state.user_ini is UserIniState.PRESENT_PREPEND_OTHER:
        p.steps.append(
            f"backup .user.ini, create anubis-prepend-chain.php chaining "
            f"{state.existing_prepend_path}, repoint .user.ini at chain"
        )
    elif state.user_ini is UserIniState.PRESENT_PREPEND_CHAIN:
        if state.chain_chained_path:
            chained_path = _webroot_path(webroot, state.chain_chained_path)
            if not ops.exists(chained_path):
                p.warnings.append(
                    f"anubis-prepend-chain.php includes {state.chain_chained_path} "
                    f"which no longer exists — chain may be stale"
                )

    if state.htaccess is HtaccessState.ABSENT:
        p.steps.append("create .htaccess with the Anubis fixup block")
    elif state.htaccess is HtaccessState.PRESENT_NO_BLOCK:
        p.steps.append("backup .htaccess, prepend the Anubis fixup block")

    if not p.steps:
        p.warnings.append("fixups already fully installed — no changes")

    return p


# --- Apply -------------------------------------------------------------------


def apply(webroot: str, ops: FileOps, dry_run: bool = False) -> FixupPlan:
    """Install or update fixups in the webroot. Returns the plan that ran."""
    p = plan(webroot, ops)
    if dry_run or not p.steps:
        return p

    _verify_safety()

    shim_path = _webroot_path(webroot, "anubis-origin-shim.php")
    user_ini_path = _webroot_path(webroot, ".user.ini")
    htaccess_path = _webroot_path(webroot, ".htaccess")
    chain_path = _webroot_path(webroot, "anubis-prepend-chain.php")

    shim_needs_write = not p.state.shim_present or (ops.read(shim_path) or "") != SHIM_PHP
    if shim_needs_write:
        ops.write(shim_path, SHIM_PHP)

    if p.state.user_ini is UserIniState.ABSENT:
        ops.write(user_ini_path, f"auto_prepend_file = {shim_path}\n")
    elif p.state.user_ini is UserIniState.PRESENT_NO_PREPEND:
        ops.backup(user_ini_path)
        text = ops.read(user_ini_path) or ""
        if not text.endswith("\n"):
            text += "\n"
        text += f"auto_prepend_file = {shim_path}\n"
        ops.write(user_ini_path, text)
    elif p.state.user_ini is UserIniState.PRESENT_PREPEND_OTHER:
        ops.backup(user_ini_path)
        existing_basename = validate_filename(
            p.state.existing_prepend_path.rsplit("/", 1)[-1],
            field="auto_prepend_file in .user.ini",
        )
        ops.write(chain_path, CHAIN_TEMPLATE.format(existing_basename=existing_basename))
        _set_prepend(ops, user_ini_path, chain_path)

    if p.state.htaccess is HtaccessState.ABSENT:
        ops.write(htaccess_path, HTACCESS_BLOCK)
    elif p.state.htaccess is HtaccessState.PRESENT_NO_BLOCK:
        ops.backup(htaccess_path)
        existing = ops.read(htaccess_path) or ""
        ops.write(htaccess_path, HTACCESS_BLOCK + "\n" + existing)

    return p


def _set_prepend(ops: FileOps, user_ini_path: str, target: str) -> None:
    text = ops.read(user_ini_path) or ""
    if PREPEND_RE.search(text):
        text = PREPEND_RE.sub(f"auto_prepend_file = {target}", text)
    else:
        if not text.endswith("\n"):
            text += "\n"
        text += f"auto_prepend_file = {target}\n"
    ops.write(user_ini_path, text)


# --- Restore (for disable) ---------------------------------------------------


@dataclass
class RestorePlan:
    webroot: str
    state: FixupState
    steps: list[str] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)


def restore_plan(webroot: str, ops: FileOps) -> RestorePlan:
    state = detect_state(webroot, ops)
    rp = RestorePlan(webroot=webroot, state=state)

    user_ini_path = _webroot_path(webroot, ".user.ini")
    htaccess_path = _webroot_path(webroot, ".htaccess")

    if state.user_ini is not UserIniState.ABSENT:
        backups = ops.glob_backups(user_ini_path)
        if backups:
            rp.steps.append(f"restore .user.ini from {backups[0]}")
        else:
            rp.steps.append("remove .user.ini (no backup — created by Anubis)")
            rp.warnings.append(".user.ini has no backup; it will be deleted, not restored")

    if state.htaccess is HtaccessState.PRESENT_WITH_BLOCK:
        backups = ops.glob_backups(htaccess_path)
        if backups:
            rp.steps.append(f"restore .htaccess from {backups[0]}")
        else:
            rp.steps.append("remove the Anubis fixup block from .htaccess (no backup)")

    if state.shim_present:
        rp.steps.append("remove anubis-origin-shim.php")
    if state.chain_present:
        rp.steps.append("remove anubis-prepend-chain.php")

    if not rp.steps:
        rp.warnings.append("no fixup artifacts found — nothing to restore")

    return rp


def restore(webroot: str, ops: FileOps, dry_run: bool = False) -> RestorePlan:
    """Tear down fixup files in the webroot. For `disable` (last vhost in group)."""
    rp = restore_plan(webroot, ops)
    if dry_run or not rp.steps:
        return rp

    state = rp.state
    user_ini_path = _webroot_path(webroot, ".user.ini")
    htaccess_path = _webroot_path(webroot, ".htaccess")
    shim_path = _webroot_path(webroot, "anubis-origin-shim.php")
    chain_path = _webroot_path(webroot, "anubis-prepend-chain.php")

    if state.user_ini is not UserIniState.ABSENT:
        if _restore_from_backup(ops, user_ini_path) is False:
            ops.unlink(user_ini_path)

    if state.htaccess is HtaccessState.PRESENT_WITH_BLOCK:
        if _restore_from_backup(ops, htaccess_path) is False:
            text = ops.read(htaccess_path) or ""
            text = _strip_htaccess_block(text)
            if not text.strip():
                ops.unlink(htaccess_path)
            else:
                ops.write(htaccess_path, text)

    if state.shim_present:
        ops.unlink(shim_path)
    if state.chain_present:
        ops.unlink(chain_path)

    return rp


def _restore_from_backup(ops: FileOps, path: str) -> bool | None:
    """Restore a file from its most recent backup.

    Returns True if restored, False if no backup exists,
    None if a backup exists but is unreadable (caller should leave file as-is).
    """
    backups = ops.glob_backups(path)
    if not backups:
        return False
    bak_content = ops.read(backups[0])
    if bak_content is None:
        return None
    ops.write(path, bak_content)
    return True


def _strip_htaccess_block(text: str) -> str:
    pattern = re.compile(
        re.escape(HTACCESS_BLOCK_START) + r".*?" + re.escape(HTACCESS_BLOCK_END) + r"\n*",
        re.DOTALL,
    )
    return pattern.sub("", text)
